### ISSUE TITLE
Getting tags does not reflect changes immediately.

### ISSUE THREAD

**Issue by freddinator** [cartalyst/tags#10]
This is my code
```php
$article = Article::where('category_id', $category->id)->where('slug', $article)->firstOrFail();
$article->setTags($request->tags);
// $request->tags is equal to "banana,apple,orange" for example
dd($article->tags);
```
The dump of the tags does not reflect the changes made, but dumping again a few moments later does. 

In contrast, this also does not work:
```php
$article = Article::create($request->all());
$article->setTags($request->tags);
dd($article->tags);
```

I'm using Laravel 5.2, with no caching in place.

**Comment by brunogaspar** [comment]
That's how Laravel works. You need to do something like `$article = $article->fresh();` to get the fresh data.
