### ISSUE TITLE
Change illuminate/database requirement

### ISSUE THREAD

**Issue by ericbarnes** [cartalyst/tags#11]
In composer you are requiring: 

```
"illuminate/database": "5.1.*|5.2.*"
```

With that, it's not possible to use Laravel 5.3. Can this not be changed to: 

```
"illuminate/database": ">= 5.1",
```

**Comment by brunogaspar** [comment]
We can perform the change but we need to ensure that nothing on 5.3 changed that might cause the code to break on 5.1 or 5.2, otherwise a new major release is going to be required.

**Comment by brunogaspar** [comment]
Did a quick test and the `lists` method needs to be changed to `pluck` as it was deprecated on 5.2.

Had to also change the `orchestra/testbench` dependency to reflect the change for the `illuminate/database` dependency.

After that, the tests passes on 5.1, 5.2 and 5.3.

@ericbarnes Do you want to send a PR with the changes or want me to do it?

**Comment by ericbarnes** [comment]
I could do it but I'm worried I'll not be able to get to it before the v5.3 release. It's supposed to come out at Laracon in two weeks and I'm pushing to get this project out before then.

**Comment by brunogaspar** [comment]
No worries, i can push the changes later today.

But i'll not be able to tag it until Laravel 5.3 is released though.
