### ISSUE TITLE
tag duplicates on Model

### ISSUE THREAD

**Issue by hayaku-fr** [cartalyst/tags#13]
Is it possible to prevent a model instance to be tagged multiple times with the same tag ?
Exemple case : 

`$tags="Test,test,tEst";
$post->setTags($tags)`

**Comment by brunogaspar** [comment]
It already prevents multiple tags as you can check [here](https://github.com/cartalyst/tags/blob/3.0/src/TaggableTrait.php#L264-L279).

If you're having that issue, you'll need to provide more information, like Laravel version, Tags version, Database Engine & Version, how to reproduce the issue etc..

I also have run a few tests locally with the following and everything worked as expected.

```php
/** @test */
public function it_can_prevent_duplicated_tags()
{
    $post = $this->createPost();

    $post->tag('foo,FOO,fOo,FoO,foO,Foo,fOO');
    $post->tag('bar,BAR,bAr,BaR,baR,Bar,bAR');

    $this->assertCount(2, Post::allTags()->get());
}
```
