### ISSUE TITLE
Append tags attribute to model

### ISSUE THREAD

**Issue by d3radicated** [cartalyst/tags#15]
Is it possible to return `$this->tags` from a model's appended attribute? It only returns an empty object.

    class Articles extends Model implements TaggableInterface
    {
        use TaggableTrait;
        
        /**
         * The table associated with the model.
         *
         * @var string
         */
        protected $table = 'articles';

        /**
         * The accessors to append to the model's array form.
         *
         * @var array
         */
        protected $appends = ['tags'];

        /**
         * Get the resource's tags.
         *
         * @param  string  $value
         * @return string
         */
        public function getTagsAttribute()
        {
            return $this->tags();
        }    
    }

**Comment by brunogaspar** [comment]
Don't recommend you to call your mutator `tags`, since the relation is also called `tags`.

Use a different name if you really want to use it this way.
