### ISSUE TITLE
Laravel 5.4

### ISSUE THREAD

**Issue by bishopm** [cartalyst/tags#16]
Hi. I've just tried updating to L 5.4 and the latest tags package depends on 5.3. Are there plans for a new release?

cartalyst/tags v3.0.0 requires illuminate/database 5.3.*

Thanks

**Comment by suwardany** [comment]
It's on the master branch, update the version to `"cartalyst/tags": "~4.0@dev"`

**Comment by bishopm** [comment]
Brilliant - thanks
