### ISSUE TITLE
namespace is necessary?

### ISSUE THREAD

**Issue by stoneworld** [cartalyst/tags#17]
In the `TaggableTraint` I find the realationship is `morphToMany` ,but in the tags table has column namespace,if use this,we just can use 

`$this->belongsToMany(static::$tagsModel, 'taggable', 'tagged', 'taggable_id', 'tag_id')
->where('namespace',static::$entityNamespace);` 
may be is not complete, why use `morphToMany` ? just this question. thanks

**Comment by brunogaspar** [comment]
The `tags` table is what holds the tags, without having duplicated tags per namespace.

The `tagged` table is what holds the relationship between a tag and a model.

So all is fine as is.
