### ISSUE TITLE
Cannot remove tagged tag which has name similar to SQL commands

### ISSUE THREAD

**Issue by imeida** [cartalyst/tags#18]
I'm using cartalyst/tags 2.1 on laravel 5.2 to develop e-learning platform for SQL. I tried to tag the SQL commands appear in each SQL query question. 

For example.
If the question's answer is `SELECT * FROM table WHERE name LIKE 'a%';`
I'll tag SELECT, WHERE and LIKE to the question.

And while I'm working on it, some of the tagged tag can't be removed. And I found 2 cases of the responses.

First case, when I submitted the changes, error returned. For example...
- BETWEEN
- LIKE
- NOT LIKE

And other case, when I submitted the changes, the tag wasn't removed and no error returned. For example...
- REGEXP

I manually fix the TaggableTrait.php file at line 245.

From...

```
->where(function ($query) use ($name) {
                $query
                    ->Where('name', $name)
                    ->orWhere('slug', $name)
                ;
            })
```

To...

`->whereRaw('(name LIKE ? OR slug LIKE ?)', [$name, $name])`

And the problem goes away.

I'm not quite sure this is cartalyst/tags bug or laravel's bug. I found this in your package, so, I decided to tell you first.

Thank you very much.

**Comment by brunogaspar** [comment]
Hello @imeida 

I'm not being able to reproduce any issue.

Please leave reproducible code and as well the database engine and version you're using.

**Comment by imeida** [comment]
I'm gonna use model named Question (already implemented TaggableInterface and use TaggableTrait) in sample code to explain here.

First, I write and run this code to tag BETWEEN and ANOTHERTAG to question id 1.
```
Route::get('/test', function()
{
    $question = \App\Models\Question::find(1);
    $question->tag(['between', 'anothertag']);
    $question = \App\Models\Question::find(1);
    dd($question->tags);
});
```
With dd, it displays collection of 2 tag correctly.

After that, I write and run this code to untag BETWEEN from question id 1. 
```
Route::get('/test2', function()
{
    $question = \App\Models\Question::find(1);
    $question->untag(['between']);
    $question = \App\Models\Question::find(1);
    dd($question->tags);
});
```
And I get this following error.
```

InvalidArgumentException in Builder.php line 503:
Illegal operator and value combination.
- in Builder.php line 503
- at Builder->where('slug', 'between', null, 'or')
- at call_user_func_array(array(object(Builder), 'where'), array('slug', 'between', null, 'or')) in Builder.php line 780
- at Builder->where('slug', 'between', null, 'or') in Builder.php line 796
- at Builder->orWhere('slug', 'between') in TaggableTrait.php line 247
...
```

I'm currently using

- CentOS 7.2
- nginx 1.10.2
- MariaDB 5.5.50
- PHP 7.0.12

Thanks you.

**Comment by brunogaspar** [comment]
Thanks @imeida i was able to reproduce the issue.

The reason it's failing is because we're passing the `$name` as the second argument and Laravel checks if that matches an [operator](https://github.com/laravel/framework/blob/7e4a5a5a2db7550de901174062a4cbafea6cbf9c/src/Illuminate/Database/Query/Builder.php#L179) so all we need to do is to pass as the second argument a `'='` and it fixes the issue.

Will follow up with a patch and will let you know once everything is pushed and tagged.
