### ISSUE TITLE
What would be the best approach to heirarchical tagging

### ISSUE THREAD

**Issue by alnutile** [cartalyst/tags#21]
Seems tags just be associated to tags, but just wanted to see if I was missing something.

For example
```
Foo
--bar
--baz
```

$tag = Tag::find(1) //foo
$tag->setTags('bar', 'baz');

```
// Get the entity object
$product = Product::find(1);

// Through a string
$product->setTags('bar');
```

Not truly heirarchical but help me to know what tags are in `Foo` and if needed find products under Foo by getting all Foo tags and then products with one of those tags.

Thanks
Al

**Comment by brunogaspar** [comment]
We actually thought about having something similar to this not so long ago, but we never got into implementing it as the need for that kinda disappeared, at least for now.

The way we were thinking was to have a parent_id column, but it just an idea, we never got into testing if it would work as expected and if it would bring up weird issues.

**Comment by alnutile** [comment]
so we would basically alter the migration, and on the Tags class make a parents function to reference this field, and a children function to make the reverse of that relationship

**Comment by brunogaspar** [comment]
@alnutile Yes, that in theory should work.
