### ISSUE TITLE
Method lists does not exist.

### ISSUE THREAD

**Issue by readergirltracey** [cartalyst/tags#22]
I get this error whenever i use untag or setTags()

**Comment by brunogaspar** [comment]
Without know what version of the package and the framework you're using, it's very difficult to help.

**Comment by readergirltracey** [comment]
I'm working on laravel 5.4, php 5.6, cartalyst/tags 2.0.1

**Comment by brunogaspar** [comment]
You should use version 4.0 instead, which is compatible with Laravel 5.4.
