### ISSUE TITLE
How to get the Tag and Tagged models to use timestamps

### ISSUE THREAD

**Issue by dongreenmedl** [cartalyst/tags#23]
Looking at the models for IlluminateTag and IlluminateTagged and they both set the $timestamps to false which causes the model to not maintain date values. I was wondering if there is an accepted way to override this value? Id like to have the tags and taggable rows contain the created_at and updated_at fields if possible.

**Comment by brunogaspar** [comment]
Hi

You can override the default models.

1) Create 2 models that extends the default ones, respectively:

```php
<?php

namespace App\Models;

class NewTaggedModel extends \Cartalyst\Tag\IlluminateTagged
{
    public $timestamps = true;
}
```

```php
<?php

namespace App\Models;

class NewTagsModel extends \Cartalyst\Tag\IlluminateTag
{
    public $timestamps = true;

    protected static $taggedModel = 'App\Models\NewTaggedModel';
}
```

2) Now that the models are created, you just need to override tags model on the model that uses the `TaggableTrait`:

```php
<?php

use App\Models\NewTagsModel;

Yourmodel::setTagsModel(NewTagsModel::class);
```

> **Note:** You can do the above on a service provider that you might have for example

3) After this, you can create a migration that adds the timestamps columns to both `tagged` and `tags` tables.

Hope it helps.

**Comment by dongreenmedl** [comment]
Ahh thank you for the helpful details. Forgive my ignorance on the matter as I should have known I can use inheritance to solve my problem. PHP isn't the normal stack I deal with on a daily basis so the other details are very helpful in integrating the new extended models. Currently looking into how service provider work in laravel and how the code block above could be used in one. I am hoping that the service provider would be able to apply the new model as the "tagsModel" for any model that is "taggable" but at the very least if its a central location that registers each model explicitly with the new model, that should be okay as well.
