### ISSUE TITLE
php 7.1 problem

### ISSUE THREAD

**Issue by Haizone** [cartalyst/tags#24]
i try to install but i get that error:

 Problem 1
    - Installation request for cartalyst/tags 5.0.* -> satisfiable by cartalyst/tags[v5.0.0].
    - cartalyst/tags v5.0.0 requires php >=7.0 -> your PHP version (7.1.11) overridden by "config.platform.php" version (5.6.25) does not satisfy that requirement.

what can i do?

**Comment by brunogaspar** [comment]
Hello @Haizone 

You seem to have something on your own `composer.json` file that's overriding the installed PHP version.

Something like

```json
"config": {
    "platform": {
        "php": "5.6.25"
    }
}
```

Other than this, this is an issue on your end.

**Comment by Haizone** [comment]
i still not understand how to fix that?
u can plz tell me step by step what to do? :/
tahnks

**Comment by brunogaspar** [comment]
> u can plz tell me step by step what to do? :/

It's quite difficult to give a step by step guide on how to fix your issue.

Something on your end is enforcing Composer to use another version of PHP.

Usually that can happen if you update your main `composer.json` file and enforce it there.

I don't know how your application is built nor how it's performing this enforcement.

You can check [this post](
https://stackoverflow.com/questions/35538071/symfony2-composer-your-php-version-5-6-18-overriden-by-config-platform-php) on Stackoverflow that covers your issue as well.
