### ISSUE TITLE
Get all tags sorted by counter

### ISSUE THREAD

**Issue by crysfel** [cartalyst/tags#25]
Hi there, thanks for maintaining this great package!

I'm wondering how can I get all tags sorted by `count`,  I'm currently getting the tags like this:

```
$tags = Song::allTags()->get();
```

It works, but I'd like to sort the tags by the counter.

**Comment by brunogaspar** [comment]
Hello @crysfel 

You can use the `orderBy()` method from Eloquent.

Example: 

```php
Song::allTags()->orderBy('count', 'DESC')->get();
```

Hope it helps.

**Comment by crysfel** [comment]
Thanks for the help! It worked!
