### ISSUE TITLE
untag() didsnt work

### ISSUE THREAD

**Issue by Haizone** [cartalyst/tags#26]
hi
 whant i use : setTag its work only to add tag
but if i try to delete tag its didnt work

if i have a 4 tags and i do update and stay only 3 its didnt delete the tag (with SetTag())

and
// Remove all the tags
$product->untag();

didnt work to

laravel 5.6

**Comment by brunogaspar** [comment]
@Haizone The issue should be now fixed.

Will do a minor refactoring on the code later to improve performance a bit.
