### ISSUE TITLE
Laravel 5.7 support

### ISSUE THREAD

**Issue by ifox** [cartalyst/tags#29]
Hi there!

Any plans to add Laravel 5.7 support in the upcoming days? That would be awesome!

I can submit a PR, but after checking Laravel 5.7 changelog, it seems like it would only consist of changing 5.6.* to 5.7.* in `composer.json`.

Thanks!

**Comment by it-can** [comment]
yeah we need this :-)

**Comment by brunogaspar** [comment]
7.0 version for Laravel 5.7 is now tagged.

Thanks!
