### ISSUE TITLE
Undefined constant 'Cartalyst\Tags\TagsServiceProvider

### ISSUE THREAD

**Issue by amanullah-1** [cartalyst/tags#30]
Hi I am getting the issue

"In app.php line 150
Undefined constant 'Cartalyst\Tags\TagsServiceProvider"
 while I am trying to 

php artisan serve 
command after following all the steps for install and configure cartalyst/tags package.
anybody can help resolving this issue?

thanks 
aman ullah

**Comment by brunogaspar** [comment]
@amanullah-1

You probably just added `Cartalyst\Tags\TagsServiceProvider` to your `config/app.php` file instead of `"Cartalyst\Tags\TagsServiceProvider"` or `Cartalyst\Tags\TagsServiceProvider::class`

One of those should fix your problem.
