### ISSUE TITLE
The typing added to setSlugGenerator now prevents it from accepting a closure.

### ISSUE THREAD

**Issue by jshannon63** [cartalyst/tags#36]
### Your Environment

- OS and Version: Mac Catalina
- PHP Version: 7.2
- Tags Version: 9.0.*

### Expected behaviour

setSlugGenerator is documented to accept a closure as an argument. We were using it like this until the latest upgrade to Laravel 6.x and Tags 9.0.

### Actual behaviour

setSlugGenerator now requires a string and therefor no longer accepts a closure. We have since updated our code to comply with this, but your docs will need updating if this was your intention.

### Steps to reproduce

*If your issue requires any specific steps to reproduce, please outline them here.*

**Comment by brunogaspar** [comment]
Sorry, will address it shortly.

**Comment by brunogaspar** [comment]
Should be fixed on both 9.x and 10.x versions.
