### ISSUE TITLE
[Proposal] Tag Relevance

### ISSUE THREAD

**Issue by darkponyhq** [cartalyst/tags#4]
A very useful feature on tagging is relevance. There could be 5 relevance levels (1-5) and a default relevance level could be set to 5. Tag relevance can be used to control the display of any kind of content and also to fine-tune related content and search results.

This feature should be optional.

**Comment by brunogaspar** [comment]
Hi,

It's an interesting feature, how do you see it behaving working?

**Comment by darkponyhq** [comment]
To get closer to the idea:

Once you add a tag through your admin system, there will be a relevance bar (think about 5 vertical bars) which will work similar to a star rating system on eCommerce websites. On hover and click you could alter the default relevance and set it to anything from 1 to 5.

on the backend this could be something like this:

```php
$product->tag('foo')->rel(3);
```
or for multiple tags
```php
$product->tag('foo:3, bar:5, baz');
```
no rel or no number would either force the default value (e.g. 5) or leave the relevance feature out altogether.

Once relevance is available we could fetch all objects with a specific tag but with relevance equal to, less than or greater than a number.

A more complete example will be a blog system. Lots of articles, multiple tags per article with difference relevance levels. I want to automatically display related articles based on tag relevance, not just tags in general.

**Comment by brunogaspar** [comment]
@darkponyhq,

Honestly, this doesn't belong to this package as tags are meant to be a simple categorization system if you will, not as a rating system or anything along those lines.

Your idea is ok, but it should be a separate package or something that you can apply on your application base.

Hope you understand!

**Comment by darkponyhq** [comment]
@brunogaspar 

The proposal was just for tags not for a rating system altogether. A rating package is far more complicated (sessions, unique votes, IP checking etc).

I referred to the rating system in order to highlight the way admins, editors and authors could add relevance to tags (like a star system).

As for the use of having relevance on tags (when tagging articles specifically), I have to highlight that publishing platforms like Escenic and CoreMedia which are used by companies like Reuters, Bild.de are using this feature and it is quite a feature.

On the other hand applying relevance on application base does not make much sense. Would you add relevance to Users for example? who is "more admin" that somebody else or "more member". It does not provide any value. Whereas with tags it makes too much sense.

I appreciate your response, if in any case you consider this I can got into more detail.

**Comment by brunogaspar** [comment]
Sorry, but i'm still failing to see why this is useful and why it should be on this package.
Probably with a proper real world example on where this would apply and be useful, would help.
