### ISSUE TITLE
Creating a tag error on pgsql

### ISSUE THREAD

**Issue by nomadme** [cartalyst/tags#9]
Having problem with creating a tag on pgsql, mysql is fine. Failing due to violation of not-null constraint on "count" column.

**Comment by brunogaspar** [comment]
Not sure if this fixes it or not (i don't have PgSQL installed at this moment) but can you try this workaround?

Swap [this](https://github.com/cartalyst/tags/blob/2.1/src/TaggableTrait.php#L217-L220) with:

```php
$tag = $this->createTagsModel()->firstOrNew([
    'slug'      => $this->generateTagSlug($name),
    'namespace' => $this->getEntityClassName(),
    'count'     => 0,
]);
```

And please see if it works as i'm not sure that we can fix this through migrations as we already have a `default(0)` on the `count` column as you can see [here](https://github.com/cartalyst/tags/blob/2.1/resources/migrations/2014_10_29_202547_migration_cartalyst_tags_create_tables.php#L50).

**Comment by nomadme** [comment]
I just tested it and returned with 2 different results.

1. Creating a tag, through Content, Pages, it works.
2. Creating a tag, through Tags itself, it doesn't.

**Comment by brunogaspar** [comment]
Thanks for the input. We'll run a few tests on our and see where is better to apply the fix or fixes.

**Comment by nomadme** [comment]
@brunogaspar Any update on this?

**Comment by suwardany** [comment]
Hello @nomadme .. Also unable to reproduce this using the default homestead box.

Please provide us with more info about your env and how to reproduce the error.

**Comment by nomadme** [comment]
Hey,

laravel/homestead (virtualbox, 0.4.0)

please see here my info.php
https://www.dropbox.com/sh/nn4wtdgc9bz02at/AAACW2tV6tLZlVg6_JR3BzZYa?dl=0




On February 5, 2016 at 2:15:44 PM, Suhayb Wardany (notifications@github.com) wrote:

Hello @nomadme .. Also unable to reproduce this using the default homestead box.

Please provide us with more info about your env and how to reproduce the error.

**Comment by suwardany** [comment]
@nomadme .. Looks pretty much the same as on my side, except for a newer version of the pdo_pgsql driver that is slightly newer on my end.

I also ran `apt-get update && apt-get upgrade` in order to ensure i have the latest versions in place.

What version of PostgreSQL are you running?

Are you attempting to use the tags package or does the error happen when creating through the extension?

**Comment by nomadme** [comment]
Thanks for looking into.

```
vagrant@homestead:~$ psql --version
psql (PostgreSQL) 9.4.4
```

Are you on Homestead 0.4.0?

I'm using it with the Platform, and with @brunogaspar 's  code provided, it able to fix the problem on creating a tag through another extension, but if I try to create a tag through its own Tags extension, error persists.

**Comment by suwardany** [comment]
I am on `0.4.0` and psql `9.4.5`

Have you altered any configurations or something?

**Comment by nomadme** [comment]
No. you mean on the extension itself?

**Comment by suwardany** [comment]
on postgre

**Comment by nomadme** [comment]
no
